apiVersion: 1
datasources:
  - name: tokleaderboard
    type: postgres
    access: proxy
    url: postgres:5432
    user: tok
    jsonData:
      database: tokleaderboard
      sslmode: disable
    secureJsonData:
      password: tok
    isDefault: true
